apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: cm-db
      # Outra maneira de referenciar o ConfigMap é passando varíavel por variável:
      # env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: cm-db
      #         key: MYSQL_ROOT_PASSWORD
      #   *Demais pares chave x valor*