apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod # Destino da requisição
  ports:
    - port: 9000 # Porta de recebimento do serviço
      targetPort: 80 # Porta de destino/pod da requisição. Caso portas origem/destino sejam iguais, descartar targetPort