apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
    - port: 9000
      targetPort: 80
      nodePort: 30000 # Porta para acesso externo ao node 30000~32767